baseURL = "https://zellyn.com/"
title = "Zellyn Hunter"
author = "Zellyn Hunter"
disqusShortname = "zellyn"
publishDir = "docs"
theme = 'etch'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.pikchr]
        Enabled = true
        ToggleDefault = true
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]


languageCode = "en-US"
enableInlineShortcodes = true

[params]
  description = "Zellyn's Website"
  # copyright = "Copyright © 2021 Zellyn Hunter"
  dark = "off"
  highlight = true
  math = true

[menu]
  # [[menu.main]]
  #   identifier = "posts"
  #   name = "posts"
  #   title = "posts"
  #   url = "/"
  #   weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "projects"
    title = "projects"
    url = "/page/projects/done"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 20
    page = "about"

  [[menu.main]]
    identifier = "resume"
    name = "resume"
    title = "resume"
    url = "/resume/"
    weight = 20
    page = "resume"

[permalinks]
  posts = "/:year:/:month:/:slug/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

[markup.tableOfContents]
  ordered = true

[markup.highlight]
  style = 'friendly'
